### ISSUE TITLE
Bug: Changes not being saved

### ISSUE THREAD

**Issue by nancikennedy** [AcidWeb/REHack#3]
I had to blow away my WTF directory because of a different issue, but when I tried to put the Rehack.lua file back it keeps getting reset to the Default single "Welcome page" every time I reload/log. I've tried manually adding new pages and they don't "stick" either. I have no lua error code, and can't figure out why the file keeps getting rewritten

**Comment by nancikennedy** [comment]
This is on Retail, with 2.4.2 installed. I also tried deleting my installation of REHack and then installed it from the 2.4.2.zip here of github.

**Comment by nancikennedy** [comment]
I also tried with versions 2.4.1, 2.4.2 and got the same result.

**Comment by AcidWeb** [comment]
It is not connected with addon version at all. Make sure that `REHack.lua` is not set to read only.

**Comment by nancikennedy** [comment]
Forgot to mention that. It was the first thing I checked, even though the file I copied over had just had a new page added before I had to reset everything.

**Comment by nancikennedy** [comment]
Well, even though it was clearly NOT marked as Read only in the Properties dialog....something with permissions was screwed up. I just decided to do a recursive removal of Read only from the _retail_ folder. Miraculously, I can now make changes to it in game that stick.
